apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-lb
  namespace: istio-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: prometheus