apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-stateful-svc
  namespace: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
    name: cql
  - port: 9160
    name: thrift
  - port: 7199
    name: jmx
  selector:
    app: cassandra