apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-stateful
  namespace: cassandra
  labels:
    app: cassandra
spec:
  serviceName: cassandra-stateful-svc
  replicas: 5
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra
        image: eu.gcr.io/deployment-strategies/cassandra:6
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_CGROUP_MEMORY_LIMIT
            value: 'true'
          - name: CASSANDRA_CLUSTER_NAME
            value: 'cassandra-stateful-svc'
          - name: CASSANDRA_PROMETHEUS_ENABLED
            value: 'true'
          - name: CASSANDRA_SEEDS
            value: 'cassandra-stateful-0.cassandra-stateful-svc.cassandra.svc.cluster.local,cassandra-stateful-1.cassandra-stateful-svc.cassandra.svc.cluster.local,cassandra-stateful-2.cassandra-stateful-svc.cassandra.svc.cluster.local,cassandra-stateful-3.cassandra-stateful-svc.cassandra.svc.cluster.local,cassandra-stateful-4.cassandra-stateful-svc.cassandra.svc.cluster.local'
          - name: LOCAL_JMX
            value: 'no'
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - name: cassandra-data
          mountPath: /cassandra_data
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 50Gi