apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-lb
  namespace: istio-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: grafana