apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
  name: jaeger-ui
  namespace: observability
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 16686
  selector:
    app: jaeger